### ISSUE TITLE
Deploying the Application

### ISSUE THREAD

**Issue by nhempen** [red-hat-academy/openshift-workshop#2]
I would change the section header "Creating a new app in the Command Line" to "Create another app in the Command Line". 
Also, I didn't see where the default passwords were indicated. The terminal doesn't show any passwords, and I didn't see them on the okd install site. I just guessed them, it might be useful to put them at the top of the Deploying the application page.

**Comment by Kloct** [comment]
Actually any password will work as long as it's not blank
I'll update the documentation for that
Thanks!
